---
# Переменные для Ног (VPN Ноды)
xray_cpu_core: "0"         # Закрепление контейнера xray на Ядре 0
irq_affinity_mask: "e"     # Маска распределения прерываний сетевой карты (e = бинарно 1110, отключаем ядро 0)

# Публичный ключ Marzban Master для авторизации нод.
# Получить его можно на мастере в файле /var/lib/marzban/mysql.db или через UI в настройках ноды
marzban_master_public_key: |
  -----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv...
  ЗАМЕНИТЕ_МЕНЯ_НА_РЕАЛЬНЫЙ_ПУБЛИЧНЫЙ_КЛЮЧ_МАСТЕРА
  -----END PUBLIC KEY-----

# Диапазоны портов, которые будут открыты для подключения клиентов
client_ports:
  - { port: "62050", proto: "tcp" } # Порт сервиса ноды
  - { port: "62051", proto: "tcp" } # Порт API Xray
  - { port: "10000-50000", proto: "udp" } # Диапазон для клиентского VPN-трафика
  - { port: "10000-50000", proto: "tcp" } # Диапазон для клиентского VPN-трафика
