[master_servers]
# IP-адрес вашей "Головы" (Marzban Master)
master-01 ansible_host=192.168.1.100 ansible_user=root

[node_servers]
# IP-адреса ваших "Ног" (Высокопроизводительные VPN Ноды)
node-01 ansible_host=192.168.1.101 ansible_user=root
node-02 ansible_host=192.168.1.102 ansible_user=root

[all:vars]
# Порт SSH по умолчанию (можно переопределить глобально)
ansible_port=22
